id: AF929793F
base_file: fFB30.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:48:40.515726
  last_modified_at: 2022-05-30 18:48:40.515730
