id: AF929793F
base_file: f7BEA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:48:40.494244
  last_modified_at: 2022-05-30 18:48:40.494248
