id: AF929793F
base_file: f4ACD.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:48:40.490312
  last_modified_at: 2022-05-30 18:48:40.490315
