id: AF929793F
base_file: fD402.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:48:40.501901
  last_modified_at: 2022-05-30 18:48:40.501905
