id: AF929793F
base_file: fF444.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:48:40.513406
  last_modified_at: 2022-05-30 18:48:40.513415
