id: AF929793F
base_file: fE4E5.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:48:40.506866
  last_modified_at: 2022-05-30 18:48:40.506869
