id: AF929793F
base_file: f1464.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:48:40.484118
  last_modified_at: 2022-05-30 18:48:40.484125
